```{r}
# Define factor levels
rotor_length <- c("7.5 cm", "8.5 cm")
leg_length   <- c("7.5 cm", "12.0 cm")
leg_width    <- c("3.2 cm", "5.0 cm")
paper_clip   <- c("No", "Yes")

# Create full 2^4 factorial design
base_design <- expand.grid(
  RotorLength = rotor_length,
  LegLength   = leg_length,
  LegWidth    = leg_width,
  PaperClip   = paper_clip
)

# Add 4 replicates per combination
design <- base_design[rep(1:nrow(base_design), each = 4), ]

# Add replicate number
design$Replicate <- rep(1:4, times = nrow(base_design))

# Add empty column for flight time
design$FlightTime_sec <- NA

# Save CSV
#write.csv(design, "helicopter_design.csv", row.names = FALSE)

#design

```
```{r}
library(tidyverse)
library(emmeans)
heli <- read_csv("helicopter_design.csv")

glimpse(heli)
heli <- heli %>%
  mutate(
    rotor    = factor(rotor),
    leg_len  = factor(leg_len),
    leg_width= factor(leg_width),
    clip     = factor(clip)
  )

# fit full factorial
fit_full <- aov(flight_time ~ rotor * leg_len * leg_width * clip, data = heli)

summary(fit_full)  # anova table for main effects + all interactions

```

# Q1. Which factors are most important to make helicopters that fly longer?

Look at ANOVA summary: larger F and smaller p values => more important
## Esimate mean and 95% CI
```{r}
emmeans(fit_main2, specs = "rotor")       # means & CI for rotor length
emmeans(fit_main2, specs = "leg_len")     # means & CI for leg length
emmeans(fit_main2, specs = "leg_width")   # means & CI for leg width
emmeans(fit_main2, specs = "clip")        # means & CI for paperclip
```


# Q2. Is there any evidence that the effect of rotor length differs by leg width?


# Q3: What would you recommend as the ideal combination to make the helicopter fly long?
